---
title: "ica dates"
editor: visual
---

```{r}
library(tidyverse)
penguins <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv')

# Check it out
head(penguins)



```

```{r}
# Create a dataset with just Adelie and Chinstrap using %in%
ACP<- penguins |>
  filter(species%in% c("Adelie","Chinstrap")) |>
  count(species)
```

```{r}
# Create a dataset with just Adelie and Chinstrap using !=
# Pipe this into `count(species)` to confirm that you only have these 2 species
 CPA <- penguins|> 
   filter(species!="Gentoo") |> 
   count(species)

```

```{r}
# First: recall the variable names
names(penguins)
```

```{r}
# Use a shortcut to keep everything but the year and island variables
penguins|>
  select(-c("year","island"))
```

```{r}
# Use a shortcut to keep only species and the penguin characteristics measured in mm
penguins|>
  select(species,ends_with("mm"))
```

```{r}
penguins|>
  select(species,contains("length"))
```

```{r}
# Change this code to sort the penguins by species, and then island name
# NOTE: The first row should be an Adelie penguin living on Biscoe island
penguins |> 
  group_by(species)|>
  count(gender)
```

```{r}
# Change this code to count the number of male/female penguins observed for each species
penguins |> 
  filter(species)|>
  count(gender)
```

```{r}
# Get today's date
as.Date(today())
```

```{r}
# Let's store this as "today" so we can work with it below
today <- as.Date(today())

# Check out the class of this object
class(today)
```

```{r}
year(today)
# What do these lines produce / what's their difference?
month(today)
```

```{r}
library(mosaic)
data("Birthdays")
head(Birthdays)
```

```{r}
penguins |> 
  filter(species != "Gentoo") |> 
  ggplot(aes(y = bill_length_mm, x = bill_depth_mm, color = species)) + 
    geom_point()
```
